llm: 
  provider: ollama
  model: phi4-mini:latest
  ollama_host: https://localhost:11434

embedding: 
  provider: ollama
  model: mxbai-embed-large:latest

vector_store:
  path: ./rag/chroma_db
  top_k: 7
  distance_threshold: 0.8

database: 
  sqlite_path: ./memory/database.db

target_database:
  type: sqlite3
  url: sqlite:///./test/example_target.db

ask:
  max_attempts: 5

message:
  context_window: 5

auth:
  secred_key: "qui-dentro-ci-va-una-stringa-lunga-e-casuale"
  access_token_expire_minutes: 60